### ISSUE TITLE
If a user only has one restaurant, redirect to that restaurant

### ISSUE THREAD

**Issue by marcpage** [marcpage/scheduling#45]
In `scheduling.py`, the `login()` method should only send them to `/welcome` if they are employees of multiple restaurants. 
Something like:

`restaurant_count = len(set([r.role.restaurant_id for r in user.roles]))`

**Comment by suryasis-hub** [comment]
Hey can you assign the issue to me.

**Comment by marcpage** [comment]
@suryasis-hub Sorry, I didn't see your comment until I completed it this morning.
