### ISSUE TITLE
[image] Create favicon for the website

### ISSUE THREAD

**Issue by marcpage** [marcpage/scheduling#52]
Having a [favicon](https://en.wikipedia.org/wiki/Favicon) would make the site look more professional.

I was thinking a red, stylized R (for restaurant). Or maybe something like the [cook emoji](https://favicon.io/emoji-favicons/cook).

It can be stored in src/ui.

It can be `.png` or `.ico`.

**Comment by marcpage** [comment]
@avichal04 You had mentioned you have a favicon. Can you create a Pull Request with it?

**Comment by avichal04** [comment]
I am actually checking whether it is looking nice or not.
Sorry for late.

**Comment by avichal04** [comment]
Just wait some times I am having a problem rn!!!

**Comment by avichal04** [comment]
Why I am having problem in committing my code.
It is showing conflicts .

**Comment by avichal04** [comment]
I having my code .
please review asap.

**Comment by marcpage** [comment]
You'll need to merge the latest changes from my main branch, then resolve the conflicts, commit and push the fixes.

**Comment by avichal04** [comment]
Got it.

**Comment by avichal04** [comment]
Where should I place the favicon files.
The 404.css is not functioning.
You have put the ".css" file outside template folder so may be that's the cause.

**Comment by avichal04** [comment]
I am now moving all the favicon and css file in the template folder.

**Comment by marcpage** [comment]
The `src/ui/template` folder should only have text files that are generated dynamically (via a call to `render_template`, usually in `src/schedule.py`. All other files to be served up by the web server should be in `src/ui`.

**Comment by avichal04** [comment]
Ok got it sir.
